#Quarkus configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=wardcare
quarkus.datasource.password=wardcare
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/wardcare
quarkus.flyway.migrate-at-start=true
%dev.quarkus.flyway.clean-at-start=true
