#Quarkus configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=wardcare
quarkus.datasource.password=wardcare
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/wardcare
#
#Flyway configuration
quarkus.flyway.migrate-at-start=true
%dev.quarkus.flyway.clean-at-start=true
#
# Hibernate configuration
quarkus.hibernate-orm.schema-management.strategy=none
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
#
#JWT configuration
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://wardcare.local
#
# Smallrye configuration
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.issuer=https://wardcare.local
smallrye.jwt.new-token.lifespan=86400
